In [5]:
#List Slicing 

nums = list(range(5))
print(nums)
print(nums[2:4])  #sub-list from element 2 to element 3(last index not included)
print(nums[2:])   #prints from index to the very last element 
print(nums[:2])   #prints from the begining of list up until one before given index
print(nums[:])    #prints everything, so python assumes beggining or ending if an index is not given 
print(nums[:-1])  #negative indices is an offset essentially. So print from 0 to -1 of what it was previously. 


[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]


In [9]:
#enumerate 
animal = ["cat", "dog", "house"]
for idx, animal in enumerate(animal):  #enumerate writtens a tuple of indices and the element
    print(idx)

0
1
2


In [12]:
#list comprehension 
nums = [0 , 1, 2, 3 ,4]
even_square = [x ** 2 for x in nums]  #x**2 squares, but important thing is that list comprehensions essentially 
#will create a new list so when wrapped in []

nums = [x**2 for x in nums if x % 2 == 0]
print(nums)

[0, 4, 16]


In [17]:
#dictionaries 
d = {'cat': 0, 'dog' : 1, 'animal' : '2'}

print(d.get("cat", 'NA'))    #default return if key isnt in the list is NA. If you were to use 
# d["NON_EXISTENT_KEY"] it would return a keytype error

for key, value in d.items():    #d.items return a tuple of key value pairs 
    print(key, value)

0
cat 0
dog 1
animal 2


In [21]:
#tuples : an immutable ordered list of values. 

t = (5, 6)
d = {(x, x + 1) : (x) for x in range(0, 6)}   #dictionary comprehension to create a list of tuples 

print(d[(1, 2)])
print(d[t])

1
5


In [22]:
#functions

#optional arguments 
def optional_args(i, x = "optional arguement"):
    print(i , x)
    
    
optional_args(0, "tennis")
optional_args(0)

0 tennis
0 optional arguement


In [23]:
#classes 

class Greeter(object):           #utilize the object keyword
    
    def __init__(self, name):    #need to pass in self because python functions are objects, and they need to know 
        print(name)              #what instance of an object to call it on. 
        
    def greet(self, loud = False):
        print(loud)
        
g = Greeter("Chiru")
g.greet()

Chiru
False


In [29]:
#NUMPY SECTION STARTING 
import numpy as np 

In [35]:
#Creating Arrays 

a = np.array([3,2,4])
print(a.shape)

print(a[0], a[1], a[2])   #numpy arrays are created as column vectors, so indexing is also done column wise. 

b = np.array([[1,2,3], [4,5,6]]) #creates a rank 2 array [1,2,3] and [4,5,6] are rows of the array 
print(b)
print(b.shape)

#essentially numpy arrays can be thought of as arrays of arrays like in java, 2 dimensional arrays 
#in a matrix format, each list is a row


(3,)
3 2 4
[[1 2 3]
 [4 5 6]]
(2, 3)
1


In [37]:
#functions to create arrays 
a = np.zeros((2,3))  #creates a 2 by 3 matrix of 0s

b = np.ones((1,2))   #creates an 1 by 2 matrix of all 1s 

c = np.full((2,2), 7) #creates a constant array

In [41]:
#indexing with numpy arrays 

a = np.array([[1,2,3], [3,4,5], [5,6,7]])

b = a[:2, 1:3]    #essentially naming row and column indexes, so from 0 to 1 rows and 1 to 2 columns
print(b)

row_r1 = a[1, :]  #comma delimits the row and column indices when slicing, so this will get the first row and all columsn
row_r2 = a[2, 0:2] # this will print out vectors 

print(row_r2)

[[2 3]
 [4 5]]
[5 6]


In [49]:
#Array Math 

x = np.array([[1,2], [3,3]], dtype = np.float64)
y = np.array([[5,6], [7,8]], dtype = np.float64)


print(x + y)    # this is element wise addition 
print(np.add(x, y))  #same thing 


print(x * y)  #this is element wise multiplication 

[[ 6.  8.]
 [10. 11.]]
[[ 6.  8.]
 [10. 11.]]
[[ 5. 12.]
 [21. 24.]]


In [52]:
# Matrix Dot Products 

print(np.dot(x, y)) #this is actual matrix multiplication, i guess to get dot products you actually need to 
#multiply by transpose 

print(np.dot(x.T, y))

[[19. 22.]
 [36. 42.]]
[[26. 30.]
 [31. 36.]]


In [54]:
# Why Broadcasting ??

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # creates an empty matrix with the same shape as x 


for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)    #this type of loop works but computing this when matrix is large is incredibly slow and time consuming, 
# hence broadcasting 




[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
#Actual Example of Broadcasting 

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 


y = x + v

print(y)    #this is how broadcasting works 

# Rules For Broadcasting: 

    #Rule 1: If two arrays do not have the same rank, prepend the shape of the lower rank array until both have 
    #        same length shapes.
    
    #Rule 2: Two arrays are said to be compatible in dimension when they have the same size in that dimension.
    #        or if one of the arrays has size 1 in that dimension. 
    
    #Rule 3: The arrays can be broadcasted together if they are compatible in all dimensions.
    
    #Rule 4: After Broadcasting, each array behaves as if it had the shape equal to its elementwise maximum 
    #        of shapes of two input arrays. 
    
    #Rule 5: In any dimension where one array had size 1 and the other array had size greater than 1, the first 
    #        array behaves as it were copied along that dimension. 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
